version: '3.7'

# 컴퓨터들
services:
    # 컴퓨터이름
    sturbucks-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/myfolder/index.js
            - ../backend:/myfolder
        ports:
            - 5000:5000

    # 컴퓨터이름
    my-database:
        image: mongo:5
        ports:
            - 27018:27017
